### PR TITLE
Create Authentication

### PR DESCRIPTION
**Pull request by maszhar**
Hi,

1. I've fixed a little logical error in SHA1 utils.

2. Then, I created an authentication program. Here are the explaination of the endpoints:

`POST /auth/login -> Log in user`

Fields
- `username : required` => User's username
- `password : required` => User's password

Response
- If that credentials are valid, the response will have status `200` and the body will :
`{
  "data": {
    "access_token": "A"
  },
  "message": "",
  "status": "success"
}`
- Otherwise, the response  status will be  `401`

`GET /auth/me -> Get information of authenticated account`

Header Fields :
- `Authorization` => `Bearer _token_`

Response :
- If the token is valid, the response is all user information except password and the status code is `200`
- Otherwise the response status is `401`

`GET /auth/logout -> Revoking access token`

Header Fields :
- `Authorization` => `Bearer _token_`

Response :
- If the token is valid, the response is all user information except password and the status code is `200` and have message `Logged out`
- Otherwise the response status is `401`

### CODE REVIEW

**Review by Endrawan — CHANGES_REQUESTED** [review]
Thank you for your PR @fikrimus35 . But before i can check your code, i want you to create generate jwt token (last time i used /login endpoint to create jwt token). So i can test the endpoint with authorization middleware. Thanks! @fikrimus35

**Comment by maszhar** [comment]
I've made db seeder for first user account. Thanks

**Review by Endrawan — CHANGES_REQUESTED** [review]
Okayy i think the auth is working perfectly. But when i try the me endpoint `/auth/me`, the User_Type didn't return correctly. Maybe you could fix it first before i can approve it?

**Comment by maszhar** [comment]
I'm sorry about that, I forgot to add Preload method when fetching user db. I've fixed that.

**Review by Endrawan — APPROVED** [review]
Perfect! it's done now!

**Pull request merged**
